{% set name = "django-constance" %}
{% set version = "4.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django_constance-{{ version }}.tar.gz
  sha256: d86e6b6a797157a4b49d0c679f1b7b9c70b1b540f36dfcda5346736997ae51bd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - wheel
    - setuptools-scm >=8
    - pip
    - setuptools >=42
  run:
    - python >={{ python_min }}
    #- django-picklefield
    - django >=4.2

test:
  imports:
    - constance
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jazzband/django-constance
  summary: Django live settings with pluggable backends, including Redis.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
