{% set name = "django-constance" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0d366439476a46bcde15f3578de4aafec862182dd7a1c814eaf5d565da7241f4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - django-picklefield

test:
  imports:
    - constance
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jazzband/django-constance
  summary: Django live settings with pluggable backends, including Redis.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
